# crime_keywords.py
CRIME_KEYWORDS = {
    "Cybercrime": ["cybercrime", "সাইবার অপরাধ", "cyber crime", "কম্পিউটার অপরাধ"],
    "Murder": ["murder", "খুন", "হত্যা", "মারধর", "জখম"],
    "Rape": ["rape", "ধর্ষণ", "গণধর্ষণ", "যৌন নির্যাতন"],
    "Theft": ["theft", "চুরি", "চুরির", "অপহরণ", "চোরাচালান"],
    "Fraud": ["fraud", "প্রতারণা", "জালিয়াতি", "ধোঁকাবাজি"],
    "Forgery": ["forgery", "জালিয়াতি", "নকল", "মিথ্যা", "জাল দলিল"],
    "Bribery": ["bribery", "ঘুষ", "ঘুষখোরি", "লাঞ্ছনা"],
    "Corruption": ["corruption", "দুর্নীতি", "দুষ্কর্ম", "অন্যায়"],
    "Money laundering": ["money laundering", "টাকা পাচার", "অর্থ পাচার", "অবৈধ অর্থ"],
    "Smuggling": ["smuggling", "পাচার", "মাদক পাচার", "অবৈধ পরিবহন"],
    "Terrorism": ["terrorism", "সন্ত্রাস", "সন্ত্রাসবাদ", "আতঙ্ক"],
    "Drug trafficking": ["drug trafficking", "মাদক পাচার", "মাদক ব্যবসা", "ড্রাগস"],
    "Acid attack": ["acid attack", "অ্যাসিড হামলা", "অ্যাসিড নিক্ষেপ", "অ্যাসিড আক্রমণ"],
    "Dowry": ["dowry", "যৌতুক", "দেনমোহর", "বরযাত্রা"],
    "Domestic violence": ["domestic violence", "ঘরোয়া হিংসা", "পারিবারিক হিংসা", "নারী নির্যাতন"],
    "Human trafficking": ["human trafficking", "মানব পাচার", "মানুষ পাচার", "শিশু পাচার"],
    "Hacking": ["hacking", "হ্যাকিং", "কম্পিউটার হ্যাকিং", "সাইবার হামলা"],
    "Child abuse": ["child abuse", "শিশু নির্যাতন", "শিশু শোষণ", "শিশু অপব্যবহার"],
    "Food adulteration": ["food adulteration", "খাদ্য ভেজাল", "খাদ্য দূষণ", "মিশ্রিত খাদ্য"],
    "Land grabbing": ["land grabbing", "জমি দখল", "ভূমি দখল", "জমি হড়প"],
    "Pollution": ["pollution", "দূষণ", "পরিবেশ দূষণ", "বায়ু দূষণ"],
    "Wildlife killing": ["wildlife killing", "বন্যপ্রাণী হত্যা", "প্রাণী হত্যা", "বন্য জীব হত্যা"],
    "Arson": ["arson", "আগুন লাগানো", "দাহকাণ্ড", "আগুন ধরানো"],
    "Counterfeiting": ["counterfeiting", "নকল মুদ্রণ", "জাল মুদ্রা", "মুদ্রা জালিয়াতি"],
    "Illegal construction": ["illegal construction", "অবৈধ নির্মাণ", "অননুমোদিত ভবন", "অবৈধ ভবন"],
    "Fake passport": ["fake passport", "জাল পাসপোর্ট", "নকল পাসপোর্ট", "মিথ্যা পাসপোর্ট"],
    "Tax evasion": ["tax evasion", "কর ফাঁকি", "কর এড়ানো", "কর চুরি"],
    "Bank fraud": ["bank fraud", "ব্যাংক প্রতারণা", "ব্যাংক জালিয়াতি", "ব্যাংক ধোঁকা"],
    "Extortion": ["extortion", "মুক্তিপণ", "ভয় দেখিয়ে টাকা", "জোর করে টাকা"]
}